name: "GITHUB build on push"
run-name: "{{ github.actor }} is launching the GITHUB build on push workflows"

on: [push]
jobs: 
  inbox-watcher-build-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source inbox watcher code
        uses: actions/checkout@v3 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: compile and build code with maven
        run: mvn --batch-mode clean install

   